function SummaryPanel({ blog }) {
  const summary = blog.detailedSummary;

  if (!summary) {
    return (
      <div className="summary-panel empty">
        <p>No analysis available for this essay yet.</p>
        <p className="hint">Run <code>npm run fetch-blogs</code> to generate summaries.</p>
      </div>
    );
  }

  return (
    <div className="summary-panel">
      <section className="summary-section theme">
        <h3>Central Theme</h3>
        <p>{summary.theme}</p>
      </section>

      <section className="summary-section">
        <h3>Summary</h3>
        <p>{summary.summary}</p>
      </section>

      <section className="summary-section">
        <h3>Key Takeaways</h3>
        <ul>
          {summary.takeaways?.map((item, i) => (
            <li key={i}>{item}</li>
          ))}
        </ul>
      </section>

      {summary.controversial && summary.controversial.length > 0 && (
        <section className="summary-section controversial">
          <h3>Points of Debate</h3>
          <ul>
            {summary.controversial.map((item, i) => (
              <li key={i}>{item}</li>
            ))}
          </ul>
        </section>
      )}

      <div className="summary-footer">
        <span className="ai-disclaimer">Analysis generated by Claude</span>
      </div>
    </div>
  );
}

export default SummaryPanel;
